---
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate PDF document
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: Rishi_Kumar_Resume.tex

      - name: Release pdf
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Rishi_Kumar_Resume.pdf
          name: Rishi_Kumar_Resume.pdf


